
export interface State {
    code: string;
    name: string;
}

export interface Country {
    code: string;
    name: string;
    states: State[] | null;
}

export const countries: Country[] = [
    { name: 'Afghanistan', code: 'AF', states: null },
    { name: 'Åland Islands', code: 'AX', states: null },
    { name: 'Albania', code: 'AL', states: null },
    { name: 'Algeria', code: 'DZ', states: null },
    { name: 'American Samoa', code: 'AS', states: null },
    { name: 'Andorra', code: 'AD', states: null },
    { name: 'Angola', code: 'AO', states: null },
    { name: 'Anguilla', code: 'AI', states: null },
    { name: 'Antarctica', code: 'AQ', states: null },
    { name: 'Antigua and Barbuda', code: 'AG', states: null },
    { name: 'Argentina', code: 'AR', states: null },
    { name: 'Armenia', code: 'AM', states: null },
    { name: 'Aruba', code: 'AW', states: null },
    { name: 'Australia', code: 'AU', states: [
        { name: 'Australian Capital Territory', code: 'ACT' },
        { name: 'New South Wales', code: 'NSW' },
        { name: 'Northern Territory', code: 'NT' },
        { name: 'Queensland', code: 'QLD' },
        { name: 'South Australia', code: 'SA' },
        { name: 'Tasmania', code: 'TAS' },
        { name: 'Victoria', code: 'VIC' },
        { name: 'Western Australia', code: 'WA' },
    ] },
    { name: 'Austria', code: 'AT', states: null },
    { name: 'Azerbaijan', code: 'AZ', states: null },
    { name: 'Bahamas', code: 'BS', states: null },
    { name: 'Bahrain', code: 'BH', states: null },
    { name: 'Bangladesh', code: 'BD', states: null },
    { name: 'Barbados', code: 'BB', states: null },
    { name: 'Belarus', code: 'BY', states: null },
    { name: 'Belgium', code: 'BE', states: null },
    { name: 'Belize', code: 'BZ', states: null },
    { name: 'Benin', code: 'BJ', states: null },
    { name: 'Bermuda', code: 'BM', states: null },
    { name: 'Bhutan', code: 'BT', states: null },
    { name: 'Bolivia', code: 'BO', states: null },
    { name: 'Bosnia and Herzegovina', code: 'BA', states: null },
    { name: 'Botswana', code: 'BW', states: null },
    { name: 'Bouvet Island', code: 'BV', states: null },
    { name: 'Brazil', code: 'BR', states: null },
    { name: 'British Indian Ocean Territory', code: 'IO', states: null },
    { name: 'Brunei Darussalam', code: 'BN', states: null },
    { name: 'Bulgaria', code: 'BG', states: null },
    { name: 'Burkina Faso', code: 'BF', states: null },
    { name: 'Burundi', code: 'BI', states: null },
    { name: 'Cambodia', code: 'KH', states: null },
    { name: 'Cameroon', code: 'CM', states: null },
    { name: 'Canada', code: 'CA', states: [
        { name: "Alberta", code: "AB" },
        { name: "British Columbia", code: "BC" },
        { name: "Manitoba", code: "MB" },
        { name: "New Brunswick", code: "NB" },
        { name: "Newfoundland and Labrador", code: "NL" },
        { name: "Northwest Territories", code: "NT" },
        { name: "Nova Scotia", code: "NS" },
        { name: "Nunavut", code: "NU" },
        { name: "Ontario", code: "ON" },
        { name: "Prince Edward Island", code: "PE" },
        { name: "Quebec", code: "QC" },
        { name: "Saskatchewan", code: "SK" },
        { name: "Yukon Territory", code: "YT" },
    ] },
    { name: 'Cape Verde', code: 'CV', states: null },
    { name: 'Cayman Islands', code: 'KY', states: null },
    { name: 'Central African Republic', code: 'CF', states: null },
    { name: 'Chad', code: 'TD', states: null },
    { name: 'Chile', code: 'CL', states: null },
    { name: 'China', code: 'CN', states: null },
    { name: 'Christmas Island', code: 'CX', states: null },
    { name: 'Cocos (Keeling) Islands', code: 'CC', states: null },
    { name: 'Colombia', code: 'CO', states: null },
    { name: 'Comoros', code: 'KM', states: null },
    { name: 'Congo', code: 'CG', states: null },
    { name: 'Congo, The Democratic Republic of the', code: 'CD', states: null },
    { name: 'Cook Islands', code: 'CK', states: null },
    { name: 'Costa Rica', code: 'CR', states: null },
    { name: 'Cote D\'Ivoire', code: 'CI', states: null },
    { name: 'Croatia', code: 'HR', states: null },
    { name: 'Cuba', code: 'CU', states: null },
    { name: 'Cyprus', code: 'CY', states: null },
    { name: 'Czech Republic', code: 'CZ', states: null },
    { name: 'Denmark', code: 'DK', states: null },
    { name: 'Djibouti', code: 'DJ', states: null },
    { name: 'Dominica', code: 'DM', states: null },
    { name: 'Dominican Republic', code: 'DO', states: null },
    { name: 'Ecuador', code: 'EC', states: null },
    { name: 'Egypt', code: 'EG', states: null },
    { name: 'El Salvador', code: 'SV', states: null },
    { name: 'Equatorial Guinea', code: 'GQ', states: null },
    { name: 'Eritrea', code: 'ER', states: null },
    { name: 'Estonia', code: 'EE', states: null },
    { name: 'Ethiopia', code: 'ET', states: null },
    { name: 'Falkland Islands (Malvinas)', code: 'FK', states: null },
    { name: 'Faroe Islands', code: 'FO', states: null },
    { name: 'Fiji', code: 'FJ', states: null },
    { name: 'Finland', code: 'FI', states: null },
    { name: 'France', code: 'FR', states: null },
    { name: 'French Guiana', code: 'GF', states: null },
    { name: 'French Polynesia', code: 'PF', states: null },
    { name: 'French Southern Territories', code: 'TF', states: null },
    { name: 'Gabon', code: 'GA', states: null },
    { name: 'Gambia', code: 'GM', states: null },
    { name: 'Georgia', code: 'GE', states: null },
    { name: 'Germany', code: 'DE', states: null },
    { name: 'Ghana', code: 'GH', states: null },
    { name: 'Gibraltar', code: 'GI', states: null },
    { name: 'Greece', code: 'GR', states: null },
    { name: 'Greenland', code: 'GL', states: null },
    { name: 'Grenada', code: 'GD', states: null },
    { name: 'Guadeloupe', code: 'GP', states: null },
    { name: 'Guam', code: 'GU', states: null },
    { name: 'Guatemala', code: 'GT', states: null },
    { name: 'Guernsey', code: 'GG', states: null },
    { name: 'Guinea', code: 'GN', states: null },
    { name: 'Guinea-Bissau', code: 'GW', states: null },
    { name: 'Guyana', code: 'GY', states: null },
    { name: 'Haiti', code: 'HT', states: null },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM', states: null },
    { name: 'Holy See (Vatican City State)', code: 'VA', states: null },
    { name: 'Honduras', code: 'HN', states: null },
    { name: 'Hong Kong', code: 'HK', states: null },
    { name: 'Hungary', code: 'HU', states: null },
    { name: 'Iceland', code: 'IS', states: null },
    { name: 'India', code: 'IN', states: null },
    { name: 'Indonesia', code: 'ID', states: null },
    { name: 'Iran, Islamic Republic Of', code: 'IR', states: null },
    { name: 'Iraq', code: 'IQ', states: null },
    { name: 'Ireland', code: 'IE', states: null },
    { name: 'Isle of Man', code: 'IM', states: null },
    { name: 'Israel', code: 'IL', states: null },
    { name: 'Italy', code: 'IT', states: null },
    { name: 'Jamaica', code: 'JM', states: null },
    { name: 'Japan', code: 'JP', states: null },
    { name: 'Jersey', code: 'JE', states: null },
    { name: 'Jordan', code: 'JO', states: null },
    { name: 'Kazakhstan', code: 'KZ', states: null },
    { name: 'Kenya', code: 'KE', states: null },
    { name: 'Kiribati', code: 'KI', states: null },
    { name: 'Korea, Democratic People\'S Republic of', code: 'KP', states: null },
    { name: 'Korea, Republic of', code: 'KR', states: null },
    { name: 'Kuwait', code: 'KW', states: null },
    { name: 'Kyrgyzstan', code: 'KG', states: null },
    { name: 'Lao People\'S Democratic Republic', code: 'LA', states: null },
    { name: 'Latvia', code: 'LV', states: null },
    { name: 'Lebanon', code: 'LB', states: null },
    { name: 'Lesotho', code: 'LS', states: null },
    { name: 'Liberia', code: 'LR', states: null },
    { name: 'Libyan Arab Jamahiriya', code: 'LY', states: null },
    { name: 'Liechtenstein', code: 'LI', states: null },
    { name: 'Lithuania', code: 'LT', states: null },
    { name: 'Luxembourg', code: 'LU', states: null },
    { name: 'Macao', code: 'MO', states: null },
    { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', states: null },
    { name: 'Madagascar', code: 'MG', states: null },
    { name: 'Malawi', code: 'MW', states: null },
    { name: 'Malaysia', code: 'MY', states: null },
    { name: 'Maldives', code: 'MV', states: null },
    { name: 'Mali', code: 'ML', states: null },
    { name: 'Malta', code: 'MT', states: null },
    { name: 'Marshall Islands', code: 'MH', states: null },
    { name: 'Martinique', code: 'MQ', states: null },
    { name: 'Mauritania', code: 'MR', states: null },
    { name: 'Mauritius', code: 'MU', states: null },
    { name: 'Mayotte', code: 'YT', states: null },
    { name: 'Mexico', code: 'MX', states: null },
    { name: 'Micronesia, Federated States of', code: 'FM', states: null },
    { name: 'Moldova, Republic of', code: 'MD', states: null },
    { name: 'Monaco', code: 'MC', states: null },
    { name: 'Mongolia', code: 'MN', states: null },
    { name: 'Montserrat', code: 'MS', states: null },
    { name: 'Morocco', code: 'MA', states: null },
    { name: 'Mozambique', code: 'MZ', states: null },
    { name: 'Myanmar', code: 'MM', states: null },
    { name: 'Namibia', code: 'NA', states: null },
    { name: 'Nauru', code: 'NR', states: null },
    { name: 'Nepal', code: 'NP', states: null },
    { name: 'Netherlands', code: 'NL', states: null },
    { name: 'Netherlands Antilles', code: 'AN', states: null },
    { name: 'New Caledonia', code: 'NC', states: null },
    { name: 'New Zealand', code: 'NZ', states: null },
    { name: 'Nicaragua', code: 'NI', states: null },
    { name: 'Niger', code: 'NE', states: null },
    { name: 'Nigeria', code: 'NG', states: null },
    { name: 'Niue', code: 'NU', states: null },
    { name: 'Norfolk Island', code: 'NF', states: null },
    { name: 'Northern Mariana Islands', code: 'MP', states: null },
    { name: 'Norway', code: 'NO', states: null },
    { name: 'Oman', code: 'OM', states: null },
    { name: 'Pakistan', code: 'PK', states: null },
    { name: 'Palau', code: 'PW', states: null },
    { name: 'Palestinian Territory, Occupied', code: 'PS', states: null },
    { name: 'Panama', code: 'PA', states: null },
    { name: 'Papua New Guinea', code: 'PG', states: null },
    { name: 'Paraguay', code: 'PY', states: null },
    { name: 'Peru', code: 'PE', states: null },
    { name: 'Philippines', code: 'PH', states: null },
    { name: 'Pitcairn', code: 'PN', states: null },
    { name: 'Poland', code: 'PL', states: null },
    { name: 'Portugal', code: 'PT', states: null },
    { name: 'Puerto Rico', code: 'PR', states: null },
    { name: 'Qatar', code: 'QA', states: null },
    { name: 'Reunion', code: 'RE', states: null },
    { name: 'Romania', code: 'RO', states: null },
    { name: 'Russian Federation', code: 'RU', states: null },
    { name: 'RWANDA', code: 'RW', states: null },
    { name: 'Saint Helena', code: 'SH', states: null },
    { name: 'Saint Kitts and Nevis', code: 'KN', states: null },
    { name: 'Saint Lucia', code: 'LC', states: null },
    { name: 'Saint Pierre and Miquelon', code: 'PM', states: null },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', states: null },
    { name: 'Samoa', code: 'WS', states: null },
    { name: 'San Marino', code: 'SM', states: null },
    { name: 'Sao Tome and Principe', code: 'ST', states: null },
    { name: 'Saudi Arabia', code: 'SA', states: null },
    { name: 'Senegal', code: 'SN', states: null },
    { name: 'Serbia and Montenegro', code: 'CS', states: null },
    { name: 'Seychelles', code: 'SC', states: null },
    { name: 'Sierra Leone', code: 'SL', states: null },
    { name: 'Singapore', code: 'SG', states: null },
    { name: 'Slovakia', code: 'SK', states: null },
    { name: 'Slovenia', code: 'SI', states: null },
    { name: 'Solomon Islands', code: 'SB', states: null },
    { name: 'Somalia', code: 'SO', states: null },
    { name: 'South Africa', code: 'ZA', states: null },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS', states: null },
    { name: 'Spain', code: 'ES', states: null },
    { name: 'Sri Lanka', code: 'LK', states: null },
    { name: 'Sudan', code: 'SD', states: null },
    { name: 'Suriname', code: 'SR', states: null },
    { name: 'Svalbard and Jan Mayen', code: 'SJ', states: null },
    { name: 'Swaziland', code: 'SZ', states: null },
    { name: 'Sweden', code: 'SE', states: null },
    { name: 'Switzerland', code: 'CH', states: null },
    { name: 'Syrian Arab Republic', code: 'SY', states: null },
    { name: 'Taiwan, Province of China', code: 'TW', states: null },
    { name: 'Tajikistan', code: 'TJ', states: null },
    { name: 'Tanzania, United Republic of', code: 'TZ', states: null },
    { name: 'Thailand', code: 'TH', states: null },
    { name: 'Timor-Leste', code: 'TL', states: null },
    { name: 'Togo', code: 'TG', states: null },
    { name: 'Tokelau', code: 'TK', states: null },
    { name: 'Tonga', code: 'TO', states: null },
    { name: 'Trinidad and Tobago', code: 'TT', states: null },
    { name: 'Tunisia', code: 'TN', states: null },
    { name: 'Turkey', code: 'TR', states: null },
    { name: 'Turkmenistan', code: 'TM', states: null },
    { name: 'Turks and Caicos Islands', code: 'TC', states: null },
    { name: 'Tuvalu', code: 'TV', states: null },
    { name: 'Uganda', code: 'UG', states: null },
    { name: 'Ukraine', code: 'UA', states: null },
    { name: 'United Arab Emirates', code: 'AE', states: null },
    { name: 'United Kingdom', code: 'GB', states: null },
    { name: 'United States', code: 'US', states: [
        { name: "Alabama", code: "AL" },
        { name: "Alaska", code: "AK" },
        { name: "American Samoa", code: "AS" },
        { name: "Arizona", code: "AZ" },
        { name: "Arkansas", code: "AR" },
        { name: "California", code: "CA" },
        { name: "Colorado", code: "CO" },
        { name: "Connecticut", code: "CT" },
        { name: "Delaware", code: "DE" },
        { name: "District Of Columbia", code: "DC" },
        { name: "Federated States Of Micronesia", code: "FM" },
        { name: "Florida", code: "FL" },
        { name: "Georgia", code: "GA" },
        { name: "Guam", code: "GU" },
        { name: "Hawaii", code: "HI" },
        { name: "Idaho", code: "ID" },
        { name: "Illinois", code: "IL" },
        { name: "Indiana", code: "IN" },
        { name: "Iowa", code: "IA" },
        { name: "Kansas", code: "KS" },
        { name: "Kentucky", code: "KY" },
        { name: "Louisiana", code: "LA" },
        { name: "Maine", code: "ME" },
        { name: "Marshall Islands", code: "MH" },
        { name: "Maryland", code: "MD" },
        { name: "Massachusetts", code: "MA" },
        { name: "Michigan", code: "MI" },
        { name: "Minnesota", code: "MN" },
        { name: "Mississippi", code: "MS" },
        { name: "Missouri", code: "MO" },
        { name: "Montana", code: "MT" },
        { name: "Nebraska", code: "NE" },
        { name: "Nevada", code: "NV" },
        { name: "New Hampshire", code: "NH" },
        { name: "New Jersey", code: "NJ" },
        { name: "New Mexico", code: "NM" },
        { name: "New York", code: "NY" },
        { name: "North Carolina", code: "NC" },
        { name: "North Dakota", code: "ND" },
        { name: "Northern Mariana Islands", code: "MP" },
        { name: "Ohio", code: "OH" },
        { name: "Oklahoma", code: "OK" },
        { name: "Oregon", code: "OR" },
        { name: "Palau", code: "PW" },
        { name: "Pennsylvania", code: "PA" },
        { name: "Puerto Rico", code: "PR" },
        { name: "Rhode Island", code: "RI" },
        { name: "South Carolina", code: "SC" },
        { name: "South Dakota", code: "SD" },
        { name: "Tennessee", code: "TN" },
        { name: "Texas", code: "TX" },
        { name: "Utah", code: "UT" },
        { name: "Vermont", code: "VT" },
        { name: "Virgin Islands", code: "VI" },
        { name: "Virginia", code: "VA" },
        { name: "Washington", code: "WA" },
        { name: "West Virginia", code: "WV" },
        { name: "Wisconsin", code: "WI" },
        { name: "Wyoming", code: "WY" },
    ] },
    { name: 'United States Minor Outlying Islands', code: 'UM', states: null },
    { name: 'Uruguay', code: 'UY', states: null },
    { name: 'Uzbekistan', code: 'UZ', states: null },
    { name: 'Vanuatu', code: 'VU', states: null },
    { name: 'Venezuela', code: 'VE', states: null },
    { name: 'Viet Nam', code: 'VN', states: null },
    { name: 'Virgin Islands, British', code: 'VG', states: null },
    { name: 'Virgin Islands, U.S.', code: 'VI', states: null },
    { name: 'Wallis and Futuna', code: 'WF', states: null },
    { name: 'Western Sahara', code: 'EH', states: null },
    { name: 'Yemen', code: 'YE', states: null },
    { name: 'Zambia', code: 'ZM', states: null },
    { name: 'Zimbabwe', code: 'ZW', states: null },
];
